import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { default as React } from 'react';
import { Container, FlexRow, Section } from '../components/shared';
import { WhaleImage } from '../components/WhaleImage';
import verifiedBadge from '../public/images/verified-badge.svg';
import styles from '../styles/Home.module.css';
import allTraits from '../utils/all-traits.json';
import { computeRandomWhaleID } from '../utils/compute-random-whale-id';
import { routes } from '../utils/routes';

type ServerHydratedProps = {
  randomWhaleIDs: number[];
};

const Home: NextPage<ServerHydratedProps> = ({ randomWhaleIDs }) => {
  return (
    <div>
      <Head>
        <title>Weird Whales</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Section>
          <Container>
            <h1 className={styles.title}>Weird Whales</h1>

            <p className={styles.description}>
              Weird Whales is a collection of <b>3,350 NFTs</b> - unique digital
              collectibles, swimming on the Ethereum Blockchain.
            </p>

            <FlexRow>
              <WhaleImage whaleID={randomWhaleIDs[0]} size={250} isAnchor />
              <WhaleImage whaleID={randomWhaleIDs[1]} size={250} isAnchor />
              <WhaleImage whaleID={randomWhaleIDs[2]} size={250} isAnchor />
            </FlexRow>
          </Container>
        </Section>
        <Section>
          <Container>
            <div className={styles.grid}>
              <Link
                href={`${routes.internal.whale}${Math.floor(
                  Math.random() * 3550,
                )}`}
              >
                <a className={styles.card}>
                  <h2>View whale information &rarr;</h2>
                  <p>Learn about rarity and attributes from a random whale</p>
                </a>
              </Link>

              <a href={routes.external.githubImages} className={styles.card}>
                <h2>Images &rarr;</h2>
                <p>View and download the source images</p>
              </a>

              <a
                href={routes.external.openSeaWWHome}
                className={styles.card}
                target="_blank"
                rel="noopener noreferrer"
              >
                <h2
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                  }}
                >
                  <span
                    style={{
                      marginRight: '10px',
                      display: 'flex',
                      alignItems: 'center',
                    }}
                  >
                    <Image
                      src={verifiedBadge}
                      width={26}
                      height={26}
                      alt="verified"
                    />
                  </span>
                  OpenSea &rarr;
                </h2>
                <p>See the floor price and recent sales.</p>
              </a>
            </div>
          </Container>
        </Section>
        <Section>
          <hr className={styles.grayLine} />
        </Section>
        <Section>
          <Container>
            <h2>Whale Types</h2>
            <table>
              <tr>
                <th>Type</th>
                <th>Number</th>
              </tr>
              <tr>
                <td>
                  <a
                    href="https://opensea.io/collection/weirdwhales?search[sortAscending]=true&search[sortBy]=PRICE&search[stringTraits][0][name]=Base&search[stringTraits][0][values][0]=Alien"
                    target="_blank"
                    rel="noreferrer"
                  >
                    Alien
                  </a>
                </td>
                <td>
                  {allTraits.filter((traits) => traits.Base === 'Alien').length}
                </td>
              </tr>
              <tr>
                <td>
                  <a
                    href="https://opensea.io/collection/weirdwhales?search[sortAscending]=true&search[sortBy]=PRICE&search[stringTraits][0][name]=Base&search[stringTraits][0][values][0]=Ape"
                    target="_blank"
                    rel="noreferrer"
                  >
                    Ape
                  </a>
                </td>
                <td>
                  {allTraits.filter((traits) => traits.Base === 'Ape').length}
                </td>
              </tr>

              <tr>
                <td>
                  <a
                    href="https://opensea.io/collection/weirdwhales?search[sortAscending]=true&search[sortBy]=PRICE&search[stringTraits][0][name]=Base&search[stringTraits][0][values][0]=Zombie"
                    target="_blank"
                    rel="noreferrer"
                  >
                    Zombie
                  </a>
                </td>
                <td>
                  {
                    allTraits.filter((traits) => traits.Base === 'Zombie')
                      .length
                  }
                </td>
              </tr>
              <tr>
                <td>
                  <a
                    href="https://opensea.io/collection/weirdwhales?search[sortAscending]=true&search[sortBy]=PRICE&search[stringTraits][0][name]=Base&search[stringTraits][0][values][0]=Normal"
                    target="_blank"
                    rel="noreferrer"
                  >
                    Normal
                  </a>
                </td>
                <td>
                  {
                    allTraits.filter((traits) => traits.Base === 'Normal')
                      .length
                  }
                </td>
              </tr>
            </table>
          </Container>
        </Section>
        <Section>
          <hr className={styles.grayLine} />
        </Section>
        <Section>
          <Container>
            <h2 className={styles.subTitle}>WEIRD WHALES</h2>
            <p>
              Weird Whales is an NFT collection created by twelve-year-old
              programmer Benyamin from London, UK who began learning to code at
              the age of five. The project started as an educational endeavour.
              Benyamin created all the base and trait layers for the whales
              (normal, zombie, ape, alien), he then generated 3350 unique
              digital collectibles programmatically using an open-source Python{' '}
              <a
                className={styles.subTextLink}
                target="_blank"
                href="https://github.com/benyaminahmed/nft-image-generator"
              >
                script
              </a>
              . The project success and backstory forms a core part of early
              NFT, generative art and digital collectible history. It has been
              featured in{' '}
              <a
                className={styles.subTextLink}
                target="_blank"
                href="https://tinyurl.com/4kwsrp4r"
              >
                The New York Times
              </a>
              ,{' '}
              <a
                className={styles.subTextLink}
                target="_blank"
                href="https://tinyurl.com/2yxjv8ae"
              >
                Business Insider
              </a>
              ,{' '}
              <a
                className={styles.subTextLink}
                target="_blank"
                href="https://tinyurl.com/3xezwxkd"
              >
                CNBC
              </a>
              ,{' '}
              <a
                className={styles.subTextLink}
                target="_blank"
                href="https://tinyurl.com/unpst3fu"
              >
                The Telegraph
              </a>
              ,{' '}
              <a
                className={styles.subTextLink}
                target="_blank"
                href="https://www.theguardian.com/technology/2021/aug/27/boy-12-makes-29000-in-non-fungible-tokens-with-digital-whale-art"
              >
                The Guardian
              </a>
              ,{' '}
              <a
                className={styles.subTextLink}
                target="_blank"
                href="https://www.itv.com/news/2021-08-27/meet-the-12-year-old-coder-who-made-290000-from-selling-whale-nfts"
              >
                ITV News
              </a>
              ,{' '}
              <a
                className={styles.subTextLink}
                target="_blank"
                href="https://www.bbc.co.uk/news/technology-58343062"
              >
                BBC
              </a>
              ,{' '}
              <a
                className={styles.subTextLink}
                target="_blank"
                href="https://nypost.com/2021/08/27/12-year-old-reportedly-set-to-earn-400k-from-selling-nfts/"
              >
                NY Post
              </a>
              ,{' '}
              <a
                className={styles.subTextLink}
                target="_blank"
                href="https://decrypt.co/76759/weird-whales-nfts-12-year-old-ethereum"
              >
                Decrypt
              </a>{' '}
              and many more. Benyamin was invited to{' '}
              <a
                className={styles.subTextLink}
                target="_blank"
                href="https://youtu.be/XHUWaLcLau8"
              >
                speak
              </a>{' '}
              about NFTs at Pembroke College, Oxford University. He is the
              youngest person to lecture at the college, founded 1624.
            </p>
          </Container>
        </Section>
        <Section>
          <hr className={styles.grayLine} />
        </Section>
        <Section>
          <Container>
            <h2 className={styles.subTitle}>THE SPECS</h2>
            <p>
              Weird Whales is a collection of NFTs - unique digital
              collectibles, swimming on the Ethereum Blockchain. 3,350 whales
              have been programmatically generated from an ocean of
              combinations, each with unique characteristics and different
              traits. Weird Whales are ERC-721 tokens on the{' '}
              <a
                className={styles.subTextLink}
                target="_blank"
                href="https://etherscan.io/address/0x96ed81c7f4406eff359e27bff6325dc3c9e042bd"
              >
                Ethereum blockchain
              </a>{' '}
              and hosted on IPFS.
            </p>
          </Container>
        </Section>
        <Section>
          <hr className={styles.grayLine} />
        </Section>
        <Section>
          <Container>
            <h2 className={styles.subTitle}>ABOUT THE DEV</h2>

            <FlexRow>
              <p>
                Benyamin Ahmed is a twelve-year-old programmer from London, UK.
                He began learning to code at the age of five. In 2021 at the
                start of the NFT bull run he launched an early profile picture
                collection (Weird Whales) with the help of the Open Source and
                NFT community. The project went viral and hit the international
                press becoming one of the most publicised NFT projects: The New
                York Times, Business Insider, CNBC, The Telegraph, The Guardian,
                ITV News, BBC, NY Post, Decrypt and many more. He is thankful
                for this community that is educating him on software
                development, web3.0, blockchains and the metaverse. You can
                follow his progress on{' '}
                <a
                  target="_blank"
                  className={styles.subTextLink}
                  href="https://twitter.com/ObiWanBenoni"
                >
                  Twitter
                </a>
                ,{' '}
                <a
                  target="_blank"
                  className={styles.subTextLink}
                  href="https://www.codewars.com/users/benyaminahmed"
                >
                  Codewars
                </a>{' '}
                and{' '}
                <a
                  target="_blank"
                  className={styles.subTextLink}
                  href="https://github.com/benyaminahmed"
                >
                  GitHub
                </a>
                .
              </p>
            </FlexRow>
          </Container>
        </Section>
      </main>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps<ServerHydratedProps> = async () => {
  const randomWhaleIDs = Array.from({ length: 3 }, computeRandomWhaleID);
  return {
    props: {
      randomWhaleIDs,
    },
    revalidate: 60 * 60 /* New whales every hour */,
  };
};
